# 上下文初始化加载
# 比application context先加载
# 应用名称
spring:
  application:
    name: base-eureka
server:
  port: 8761
eureka:
  instance:
    hostname: eureka001
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
